name: unit-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          # https://github.com/actions/go-versions/blob/main/versions-manifest.json
          go-version: "stable"
        id: go

      - name: golangci-lint
        uses: ./.github/actions/golangci-lint

      - name: Build
        run: make build

      - name: Unit tests
        run: make test
